server:
  port: 8809

spring:
  datasource:
    name: mysql_test
    type: com.alibaba.druid.pool.DruidDataSource
    #druid\u76F8\u5173\u914D\u7F6E
    druid:
      driver-class-name: com.mysql.jdbc.Driver
      #\u57FA\u672C\u5C5E\u6027
      url: jdbc:mysql://127.0.0.1:3306/test?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: 123456
      #\u914D\u7F6E\u521D\u59CB\u5316\u5927\u5C0F/\u6700\u5C0F/\u6700\u5927
      initial-size: 1
      min-idle: 1
      max-active: 20
      #\u83B7\u53D6\u8FDE\u63A5\u7B49\u5F85\u8D85\u65F6\u65F6\u95F4
      max-wait: 60000
      #\u95F4\u9694\u591A\u4E45\u8FDB\u884C\u4E00\u6B21\u68C0\u6D4B\uFF0C\u68C0\u6D4B\u9700\u8981\u5173\u95ED\u7684\u7A7A\u95F2\u8FDE\u63A5
      time-between-eviction-runs-millis: 60000
      #\u4E00\u4E2A\u8FDE\u63A5\u5728\u6C60\u4E2D\u6700\u5C0F\u751F\u5B58\u7684\u65F6\u95F4
      min-evictable-idle-time-millis: 300000
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/test
    username: root
    password: 123456


  devtools:
    remote:
      restart:
        enabled: true
    restart:
      additional-paths: aproject/src/main/java
      exclude: static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.aproject.beans
  #\u5F00\u542FMyBatis\u7684\u4E8C\u7EA7\u7F13\u5B58
  configuration:
    cache-enabled: true

tymeleaf:
  model: HTML5
  encoding: UTF-8
  prefix: classpath:/templates/
  suffix: .html
  content-type: text/html
  cache: false